= Aufgabe: Zahlen als Strings ausschreiben

Die Aufgabe hier ist, eine Funktion zu schreiben,
die eine Zahl als `int` erwartet und die einen String
zurückgibt, der die Zahl ausschreibt.

== Beispiele

*Beispiele (Normalfall):*

* 143 -> "einhundertdreiundvierzig"
* 53 -> "dreiundfünfzig"
* 7 -> "sieben"
* 258 -> "zweihundertachtundfünfzig"

*Beispiele (Sonderfälle):*

* 12 -> "zwölf"
* 20 -> "zwanzig"
* 131 -> "einhunderteinunddreißig"
* 1 -> "eins"
* 0 -> "null"
* 258756 -> "zweihundertachtundfünfzigtausendsiebenhundertsechsundfünfzig"

== Vorgehensweise:

Wir entwickeln zunächst ein Konzept, wie wir die Aufgabe lösen können.
Dies visualisieren wir mit einem Ablaufdiagramm, das die grobe Struktur
der Funktion zeigt.

Anschließend identifizieren wir die Teilfunktionen, die sich aus dem
Ablaufdiagramm ergeben.
Für diese Teilfunktionen erzeugen wir jeweils eine Funktion und einen Test,
bevor wir dann die jeweilige Funktion implementieren.

Das Ablaufdiagramm mit Überlegungen zu Funktionen findet sich hier:

* link:docs/ablauf.excalidraw.svg[]

== Struktur des Repos

Das Repository enthält die Aufgaben im Verzeichnis `zahlen`, sowie eine
Variante mit Hinweisen und die Lösung in den entsprechenden Verzeichnissen.

== Zusatzaufgaben (ohne Lösung)

* Gibt es weitere Sonderfälle, die wir noch nicht behandelt haben?
  Finden Sie solche Fälle, falls vorhanden, schreiben Sie Tests, die diese Fälle aufdecken
  und passen Sie die Funktion NumberString oder die Hilfsfunktionen entsprechend an.

* Erweitern Sie die Funktion NumberString,
  so dass sie auch Zahlen mit mehr als 3 Stellen
  sowie negative Zahlen behandeln kann.

* Schreiben Sie in einem separaten Package ein `main`-Programm, dass den Benutzer nach einer
  Zahl fragt und den entsprechenden String ausgibt. Dieses Programm soll die Funktion
  NumberString verwenden.
